In [286]:
import pandas as pd

crime_data = pd.read_excel("data/london-crime-dataset-01-04-2021-to-31-03-2025.xlsx")
crime_data

,Month_Year,Area Type,Borough_SNT,Area name,Area code,Offence Group,Offence Subgroup,Measure,Financial Year,FY_FYIndex,Count,Refresh Date
0,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,ARSON AND CRIMINAL DAMAGE,ARSON,Offences,fy21-22,21-22_01,6,2025-04-05
1,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Positive Outcomes,fy21-22,21-22_01,9,2025-04-05
2,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,BURGLARY,BURGLARY - BUSINESS AND COMMUNITY,Positive Outcomes,fy21-22,21-22_01,1,2025-04-05
3,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,BURGLARY,BURGLARY - BUSINESS AND COMMUNITY,Offences,fy21-22,21-22_01,11,2025-04-05
4,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,MISCELLANEOUS CRIMES AGAINST SOCIETY,MISC CRIMES AGAINST SOCIETY,Positive Outcomes,fy21-22,21-22_01,2,2025-04-05
...,...,...,...,...,...,...,...,...,...,...,...,...
789727,2025-03-01,Safer Neighbourhood Teams,Westminster West End,West End (NOT ACTIVE),E05000649,THEFT,SHOPLIFTING,Positive Outcomes,fy24-25,24-25_01,1,2025-04-05
789728,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,SEXUAL OFFENCES,RAPE,Offences,fy24-25,24-25_01,1,2025-04-05
789729,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,SEXUAL OFFENCES,RAPE,Positive Outcomes,fy24-25,24-25_01,1,2025-04-05
789730,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,THEFT,SHOPLIFTING,Offences,fy24-25,24-25_01,1,2025-04-05
789731,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,VEHICLE OFFENCES,THEFT FROM A VEHICLE,Offences,fy24-25,24-25_01,1,2025-04-05

In [287]:
boroughs = [
    "Barking and Dagenham",
    "Barnet",
    "Bexley",
    "Brent",
    "Bromley",
    "Camden",
    "Croydon",
    "Ealing",
    "Enfield",
    "Greenwich",
    "Hackney",
    "Hammersmith and Fulham",
    "Haringey",
    "Harrow",
    "Havering",
    "Hillingdon",
    "Hounslow",
    "Islington",
    "Kensington and Chelsea",
    "Kingston upon Thames",
    "Lambeth",
    "Lewisham",
    "Merton",
    "Newham",
    "Redbridge",
    "Richmond upon Thames",
    "Southwark",
    "Sutton",
    "Tower Hamlets",
    "Waltham forest",
    "Wandsworth",
    "Westminster",
]

capitalize_exceptions = ["a", "an", "and", "of", "in", "on", "for", "the", "to", "with"]


def get_borough(borough_snt: str) -> str:
    lowered_borough_snt = borough_snt.lower()
    for borough_name in boroughs:
        if borough_name.lower() in lowered_borough_snt:
            return borough_name
    return "Unknown"


def fix_case(string: str) -> str:
    split = string.split(" ")
    for i, word in enumerate(split):
        if word.lower() in capitalize_exceptions:
            split[i] = word.lower()
        else:
            split[i] = word.capitalize()
    return " ".join(split)


crime_data["Borough"] = crime_data["Borough_SNT"].apply(get_borough)

crime_data["Offence Group Fixed"] = crime_data["Offence Group"].apply(fix_case)
crime_data["Offence Subgroup Fixed"] = crime_data["Offence Subgroup"].apply(fix_case)

crime_data

,Month_Year,Area Type,Borough_SNT,Area name,Area code,Offence Group,Offence Subgroup,Measure,Financial Year,FY_FYIndex,Count,Refresh Date,Borough,Offence Group Fixed,Offence Subgroup Fixed
0,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,ARSON AND CRIMINAL DAMAGE,ARSON,Offences,fy21-22,21-22_01,6,2025-04-05,Barking and Dagenham,Arson and Criminal Damage,Arson
1,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Positive Outcomes,fy21-22,21-22_01,9,2025-04-05,Barking and Dagenham,Arson and Criminal Damage,Criminal Damage
2,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,BURGLARY,BURGLARY - BUSINESS AND COMMUNITY,Positive Outcomes,fy21-22,21-22_01,1,2025-04-05,Barking and Dagenham,Burglary,Burglary - Business and Community
3,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,BURGLARY,BURGLARY - BUSINESS AND COMMUNITY,Offences,fy21-22,21-22_01,11,2025-04-05,Barking and Dagenham,Burglary,Burglary - Business and Community
4,2021-04-01,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,MISCELLANEOUS CRIMES AGAINST SOCIETY,MISC CRIMES AGAINST SOCIETY,Positive Outcomes,fy21-22,21-22_01,2,2025-04-05,Barking and Dagenham,Miscellaneous Crimes Against Society,Misc Crimes Against Society
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789727,2025-03-01,Safer Neighbourhood Teams,Westminster West End,West End (NOT ACTIVE),E05000649,THEFT,SHOPLIFTING,Positive Outcomes,fy24-25,24-25_01,1,2025-04-05,Westminster,Theft,Shoplifting
789728,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,SEXUAL OFFENCES,RAPE,Offences,fy24-25,24-25_01,1,2025-04-05,Westminster,Sexual Offences,Rape
789729,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,SEXUAL OFFENCES,RAPE,Positive Outcomes,fy24-25,24-25_01,1,2025-04-05,Westminster,Sexual Offences,Rape
789730,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,THEFT,SHOPLIFTING,Offences,fy24-25,24-25_01,1,2025-04-05,Westminster,Theft,Shoplifting
789731,2025-03-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,VEHICLE OFFENCES,THEFT FROM A VEHICLE,Offences,fy24-25,24-25_01,1,2025-04-05,Westminster,Vehicle Offences,Theft From a Vehicle

In [288]:
crime_data.groupby("Borough").size()

Borough
Barking and Dagenham      22185
Barnet                    27339
Bexley                    18301
Brent                     30119
Bromley                   26151
Camden                    24919
Croydon                   30816
Ealing                    28003
Enfield                   28034
Greenwich                 26921
Hackney                   27126
Hammersmith and Fulham    22820
Haringey                  25765
Harrow                    22872
Havering                  20639
Hillingdon                23843
Hounslow                  22814
Islington                 23156
Kensington and Chelsea    20717
Kingston upon Thames      16279
Lambeth                   30854
Lewisham                  25162
Merton                    19906
Newham                    30544
Redbridge                 24783
Richmond upon Thames      16897
Southwark                 28253
Sutton                    18529
Tower Hamlets             24660
Unknown                    6710
Waltham forest            25672
Wandsworth                25688
Westminster               23255
dtype: int64

In [289]:
crime_data.groupby("Offence Group").size()

Offence Group
ARSON AND CRIMINAL DAMAGE                53012
BURGLARY                                 68682
DRUG OFFENCES                            84955
FRAUD AND FORGERY                          413
MISCELLANEOUS CRIMES AGAINST SOCIETY     31255
NFIB FRAUD                                  34
POSSESSION OF WEAPONS                    27302
PUBLIC ORDER OFFENCES                    89402
ROBBERY                                  46244
SEXUAL OFFENCES                          55027
THEFT                                   126270
VEHICLE OFFENCES                         97289
VIOLENCE AGAINST THE PERSON             109847
dtype: int64

In [290]:
crime_by_date = crime_data.groupby("Month_Year")
crime_by_date.size()

Month_Year
2021-04-01    16169
2021-05-01    16120
2021-06-01    16164
2021-07-01    16470
2021-08-01    15515
2021-09-01    16169
2021-10-01    16862
2021-11-01    16779
2021-12-01    16345
2022-01-01    16557
2022-02-01    16536
2022-03-01    17253
2022-04-01    15875
2022-05-01    17015
2022-06-01    16910
2022-07-01    16618
2022-08-01    16436
2022-09-01    16890
2022-10-01    16776
2022-11-01    16513
2022-12-01    15534
2023-01-01    16249
2023-02-01    15939
2023-03-01    16773
2023-04-01    15628
2023-05-01    16665
2023-06-01    16561
2023-07-01    16619
2023-08-01    16404
2023-09-01    16839
2023-10-01    16484
2023-11-01    16384
2023-12-01    15962
2024-01-01    16616
2024-02-01    16491
2024-03-01    15852
2024-04-01    15687
2024-05-01    15738
2024-06-01    16129
2024-07-01    16376
2024-08-01    16002
2024-09-01    17013
2024-10-01    16792
2024-11-01    16978
2024-12-01    16379
2025-01-01    16915
2025-02-01    17096
2025-03-01    17655
dtype: int64

In [291]:
import json

known_boroughs = crime_data[crime_data["Borough"] != "Unknown"]
processed_data = {
    "total": crime_data["Count"].sum().item(),
    "total_known_borough": known_boroughs["Count"].sum().item(),
    "dates": {},
}

for date, date_group in crime_by_date:
    date_string = date.strftime("%Y-%m-%d")
    known_boroughs_by_date = date_group[date_group["Borough"] != "Unknown"]
    processed_data["dates"][date_string] = {
        "total": date_group["Count"].sum().item(),
        "total_known_borough": known_boroughs_by_date["Count"].sum().item(),
        "boroughs": {},
    }
    for borough, borough_group in date_group.groupby("Borough"):
        processed_data["dates"][date_string]["boroughs"][borough] = {
            "total": borough_group["Count"].sum().item(),
            "offence_groups": {},
        }
        for offence_group, offence_group_group in borough_group.groupby("Offence Group Fixed"):
            processed_data["dates"][date_string]["boroughs"][borough]["offence_groups"][offence_group] = {
                "total": offence_group_group["Count"].sum().item(),
                "offence_subgroups": {},
            }
            for offence_subgroup, offence_subgroup_group in offence_group_group.groupby("Offence Subgroup Fixed"):
                processed_data["dates"][date_string]["boroughs"][borough]["offence_groups"][offence_group][
                    "offence_subgroups"][offence_subgroup] = offence_subgroup_group["Count"].sum().item()
    # Move the "Unknown" borough to the end of the dictionary
    unknown_borough = processed_data["dates"][date_string]["boroughs"].pop("Unknown")
    processed_data["dates"][date_string]["boroughs"]["Unknown"] = unknown_borough

crime_data_json = json.dumps(processed_data, indent=4)
with open("src/london_crime_data.json", "w") as file:
    file.write(crime_data_json + "\n")